"use client";

import { useEffect, useMemo, useState } from "react";
import TopBar from "@/components/TopBar";
import BottomNav from "@/components/BottomNav";

type U={id:string;name:string;unions?:{id:string;name:string}[]}; type D={id:string;name:string;upazilas?:U[]}; type V={id:string;name:string;districts?:D[]};
type S={id:string;name:string;description?:string;category?:{name:string};district?:{name:string};upazila?:{name:string};union?:{name:string};area?:{name:string};verificationStatus:string;divisionId?:string;districtId?:string;upazilaId?:string};

export default function Search(){
 const [loc,setLoc]=useState<V[]>([]),[division,setDivision]=useState(""),[district,setDistrict]=useState(""),[upazila,setUpazila]=useState(""),[q,setQ]=useState(""),[items,setItems]=useState<S[]>([]),[loading,setLoading]=useState(false);
 useEffect(()=>{setQ(new URLSearchParams(window.location.search).get("q")||"");fetch("/api/locations").then(r=>r.json()).then(j=>setLoc(j.data||[])).catch(()=>setLoc([]));},[]);
 const v=loc.find(x=>x.id===division),d=v?.districts?.find(x=>x.id===district); const districts=useMemo(()=>division?(v?.districts||[]):loc.flatMap(x=>x.districts||[]),[loc,v,division]);
 async function search(e?:React.FormEvent){e?.preventDefault();setLoading(true);try{const p=new URLSearchParams();if(q.trim())p.set("q",q.trim());if(division)p.set("divisionId",division);if(district)p.set("districtId",district);if(upazila)p.set("upazilaId",upazila);const r=await fetch("/api/directory/search?"+p);const j=await r.json();let base:S[]=r.ok?(j.data||[]):[];let local:S[]=[];try{local=JSON.parse(localStorage.getItem("bdld_listings")||"[]").map((x:any)=>({id:x.id,name:x.name,description:x.description,phone:x.phone,verificationStatus:"UNVERIFIED",category:{name:x.category||"অন্যান্য"},district:{name:x.district},upazila:{name:x.upazila},union:{name:x.union},area:{name:x.area},divisionId:x.divisionId,districtId:x.districtId,upazilaId:x.upazilaId}));}catch{} const needle=q.trim().toLowerCase();local=local.filter(s=>(!needle||[s.name,s.description,s.district?.name,s.upazila?.name,s.union?.name,s.area?.name].some(x=>(x||"").toLowerCase().includes(needle)))&&(!division||s.divisionId===division)&&(!district||s.districtId===district)&&(!upazila||s.upazilaId===upazila));setItems([...local,...base.filter(b=>!local.some(l=>l.id===b.id))].slice(0,100));}catch{setItems([])}setLoading(false);}
 useEffect(()=>{const t=setTimeout(()=>search(),0);return()=>clearTimeout(t)},[q,district,upazila]);
 return <main className="ps-page"><TopBar title="খুঁজুন" subtitle="সারা বাংলাদেশ" backHref="/"/><div className="ps-content"><form onSubmit={search} className="ps-search"><span className="ps-search-icon">🔍</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ব্যবসা, ডাক্তার, স্কুল, সেবা..." aria-label="Search"/></form><div className="ps-filters"><select value={division} onChange={e=>{setDivision(e.target.value);setDistrict("");setUpazila("")}} className="ps-select"><option value="">সব বিভাগ</option>{loc.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={district} onChange={e=>{setDistrict(e.target.value);setUpazila("")}} className="ps-select"><option value="">সব জেলা</option>{districts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={upazila} disabled={!district} onChange={e=>setUpazila(e.target.value)} className="ps-select"><option value="">সব উপজেলা</option>{d?.upazilas?.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><button type="submit" className="ps-btn-primary ps-btn-block" style={{marginBottom:16}}>{loading?"খুঁজছে...":"খুঁজুন"}</button><div className="ps-section-head"><h2>{loading?"খুঁজছে...":`${items.length}টি ফলাফল`}</h2></div>{items.length===0&&!loading?<div className="ps-empty"><div className="ps-empty-icon">🔍</div><h2>কোনো ফলাফল নেই</h2><p>অন্য কীওয়ার্ড বা লোকেশন দিয়ে চেষ্টা করুন।</p></div>:<div className="ps-list">{items.map(s=><a key={s.id} href={`/services/${s.id}`} className="ps-list-card"><div className="ps-list-top"><strong>{s.name}</strong>{s.verificationStatus!=="UNVERIFIED"&&<span className="ps-badge">✓ Verified</span>}</div><p className="ps-list-loc">📍 {[s.area?.name,s.union?.name,s.upazila?.name,s.district?.name].filter(Boolean).join(", ")}{s.category?.name?` · ${s.category.name}`:""}</p>{s.description&&<p className="ps-list-desc">{s.description}</p>}</a>)}</div>}</div><BottomNav active="search"/></main>;
}
